# Generated by Django 5.1 on 2024-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_feature_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='color_name',
            field=models.IntegerField(choices=[(0, 'primary'), (1, 'success'), (2, 'danger'), (3, 'dark'), (4, 'secondary'), (5, 'warning')], default=1),
        ),
    ]
