# Generated by Django 5.1 on 2024-09-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_feature_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='color_name',
            field=models.CharField(choices=[('primary', 'primary'), ('success', 'success'), ('danger', 'danger'), ('dark', 'dark'), ('secondary', 'secondary'), ('warning', 'warning')], default='success', max_length=20),
        ),
    ]
